<?php
         error_reporting(-1);
         ini_set('display_errors', 'On');
         set_error_handler("var_dump");

         // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
         $ch = curl_init();
         
         curl_setopt($ch, CURLOPT_URL, "https://api.sparkpost.com/api/v1/transmissions");
         curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
         curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n    \"options\": {\n      \"sandbox\": false\n    },\n    \"content\": {\n      \"from\": \"danielgraysoft@gmail.com\",\n      \"subject\": \"Message from Daniel Gray Website\",\n      \"text\": \"Flo Mida\"\n    },\n    \"recipients\": [{ \"address\": \"jeff.rudesyle@gmail.com\" }]\n}");
         curl_setopt($ch, CURLOPT_POST, 1);
         
         $headers = array();
         $headers[] = "Authorization: 9f44e0a8bbc377d4135dc23e0132cfff552b29fd";
         $headers[] = "Content-Type: application/json";
         curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
         
         $result = curl_exec($ch);
         if (curl_errno($ch)) {
             echo 'Error:' . curl_error($ch);
         }
         curl_close ($ch);      
?>         